rule all:
     input: 'spectrum.png'
rule plot:
     input: '{a}.py', 'Criminale.txt', 'classical.csv', 'primitive.csv'
     output: '{a}.png'
     shell: 'python {input}'
rule run:
     input: '{a}.py'
     output: '{a}.csv'
     shell: 'python {input}'
rule clean:
     shell: 'rm -rf *~ *.csv *.png'
